version: '3.1'

services:
  redis:
    image: bitnami/redis
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=c95a1be590bcba387d4926fc88b37c44c7a46615c934a89f21dde2dbf52e87e4
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER : postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  # mongo:
    # image: mongo
    # restart: always
    # ports:
      # - 27017:27017
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: admin
    # volumes:
      # - ./danko-data/mongo:/data/db

#  elasticsearch:
#     image: elasticsearch:7.17.5
#     restart: always
#     ports:
#       - 9200:9200
#       - 9300:9300

#  kibana:
#     image: kibana:7.17.5
#     restart: always
#     ports:
#       - 5601:5601
